# ﻿シナリオID
scenario_id = 1

# シミュレーション回数
num_simulations = 50

# 通信可能距離
comm_range = 200

# 生成車両数
num_vehicles = 400

# 避難地A行きの車両数
vehicles_to_shelter_A = 200

# 避難地b行きの車両数
vehicles_to_shelter_B = 200

# 避難地Aの収容台数
shelter_A_capacity = 200

# 避難地Bの収容台数
shelter_B_capacity = 200

# 車両生成間隔
vehicle_interval = 5

# 積極的経路変更者の平均
active_route_change_mean = 30

# 積極的経路変更者の分散
active_route_change_var = 15

# 慎重的経路変更者の平均
cautious_route_change_mean = 90

# 慎重的経路変更者の分散
cautious_route_change_var = 20

# 収容率閾値
shelter_capacity_threshold = 1

# 津波予兆開始時刻
tsunami_sign_start_time = 300

# 津波予兆終了時間
tsunami_sign_end_time = 400

# 逆走動機閾値始点
motivation_threshold_start = 800

# 逆走動機閾値終点
motivation_threshold_end = 1000

# 逆走動機最小閾値始点
min_motivation_start = 500

# 逆走動機最小閾値終点
min_motivation_end = 700

# 積極的逆走者始点
positive_lanechange_start = 900

# 積極的逆走者終点
positive_lanechange_end = 1100

# 慎重的逆走者始点
negative_lanechange_start = 800

# 慎重的逆走者終点
negative_lanechange_end = 1100

# ドライバーの視認距離
driver_visibility_distance = 30

# 正の同調性
positive_majority_bias = 100

# 負の同調性
negative_majority_bias = 100

# 避難地を混雑と感じる閾値積極者
active_shelter_occupancy_rate_threshold_start = 0.65

active_shelter_occupancy_rate_threshold_end = 0.8

cautious_shelter_occupancy_rate_threshold_start = 0.8

cautious_shelter_occupancy_rate_threshold_end = 0.95
