scenario_id = 4
num_simulations = 50
comm_range = 200
num_vehicles = 300
vehicle_interval = 5
shelter_capacity_threshold = 1.0
driver_visibility_distance = 50
following_rate = 0.2
active_route_change_mean = 30.0
active_route_change_var = 15.0
positive_lanechange_start = 900
positive_lanechange_end = 1100
active_shelter_occupancy_rate_threshold_start = 0.65
active_shelter_occupancy_rate_threshold_end = 0.8
cautious_route_change_mean = 120.0
cautious_route_change_var = 15.0
negative_lanechange_start = 800
negative_lanechange_end = 1100
cautious_shelter_occupancy_rate_threshold_start = 0.8
cautious_shelter_occupancy_rate_threshold_end = 0.95
tsunami_sign_start_time = 300
tsunami_sign_end_time = 400
motivation_threshold_start = 800
motivation_threshold_end = 1000
min_motivation_start = 500
min_motivation_end = 700
positive_majority_bias = 100.0
negative_majority_bias = 100.0
shelter_A_capacity = 150
vehicles_to_shelter_A = 150
shelter_B_capacity = 150
vehicles_to_shelter_B = 150
